### ISSUE TITLE
Document the package.json scripts

### ISSUE THREAD

**Issue by sangimed** [fregante/browser-extension-template#42]
Hello, 

Would it be a good idea providing a brief description + example of each script in the `package.json` file. For example in my case, I'm trying to load the unpacked extension in chrome (after doing `npm run watch`) but doesn't seem to be working (`
Could not load background script 'browser-polyfill.min.js'. Could not load manifest.`). Maybe it's not the right way of doing it 🤷‍♂️ 

Thank you in advance.

**Comment by fregante** [comment]
> in the `package.json` file

This is not possible, but documentation can be added to the readme

**Comment by janmechtel** [comment]
Maybe I can help. Do you mean to explain how/when to use the "npm run watch"  "web-ext run" for Chrome and FIrefox in the readme?

**Comment by fregante** [comment]
Yes, but web-ext only needs a mention because it’s not used here directly and it’s not technically required. 

It’d be great to add a “getting started” section to replace “how to use this template”, with all the steps to start, e.g. “use template”, check out newly-created repo, npm install, npm run watch, how to open the extension in the browser (Refined GitHub’s contributing.md) has some text you can copy for this. 

Also separately we’d also need a “publishing” section that explains the GitHub Actions setup.

**Comment by janmechtel** [comment]
>(Refined GitHub’s contributing.md) has some text you can copy for this.
what do you mean with this?

I've started on a [branch on my fork](https://github.com/janmechtel/browser-extension-template/tree/more-documentation-getting-started), please let me know if this should be done differently.

If you can please have a look and:

1. guide me if you think it should go in a different direction.
1. have a look at some todos and share knowledge if you have on them

I've taken an opinion and would recommend web-ext. If you want me to make the manual loading the default and move web-ext to optional, let me know. 

Thanks for all the work, i hope i can contribute some back!

**Comment by fregante** [comment]
For discussion you can open a draft PR
