### ISSUE TITLE
Lint css error, fetch tags error, duplicated addon once published

### ISSUE THREAD

**Issue by icetbr** [fregante/browser-extension-template#85]
Hi there, I had  few bumps using the Actions. I manage to get around them by commenting stuff, but I though I should mention.

![image](https://user-images.githubusercontent.com/1111617/179220282-21daad1b-eaf8-4c29-b551-d09642eca98f.png)

![image](https://user-images.githubusercontent.com/1111617/179220185-419b0bf7-383a-4f61-8d8e-651f8e70bbd6.png)

Also, when the addon was published to the Firefox developer hub, it got duplicated, because I had previously uploaded it manually. I imagine there is some instruction missing related to the geck.id?

**Comment by fregante** [comment]
The first bug was fixed in v2 of that action: https://github.com/fregante/daily-version-action/pull/19

The second error is because all the CSS files were deleted, so you can delete stylelint, I assume this is the line failing: https://github.com/fregante/browser-extension-template/blob/faf9fe9f86a09c87701ab7f419e06fac03aae2c8/package.json#L7
